#!/bin/bash
set -e

# Setting package version
VERSION='%VERSION%'
RUN_VERSION=$2
ARG=$1

/usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'chmod 777 /tmp' > /dev/null 2>&1
/usr/sbin/chroot /opt/gluu-server /bin/su - root -c '/tmp/system_user.list' > /dev/null 2>&1
/usr/sbin/chroot /opt/gluu-server /bin/su - root -c '/tmp/system_group.list' > /dev/null 2>&1

/bin/cp -a /etc/resolv.conf /opt/gluu-server/etc/ > /dev/null 2>&1

if [ -e /etc/init.d/gluu-server ]; then
    update-rc.d gluu-server defaults
fi

if [ "$1" = "configure" ]; then
  if [ -z "$RUN_VERSION" ] || [ "$RUN_VERSION" = "$VERSION" ]; then
    echo "Starting gluu-server ..."
    sleep 1
    /etc/init.d/gluu-server start
    sleep 5
    /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '/opt/gluu/bin/install.py'
    rm -rf /opt/gluu-server/etc/hosts
    rm -rf /opt/gluu-server/etc/hostname
    mv /opt/gluu-server/etc/hosts.original /opt/gluu-server/etc/hosts
    mv /opt/gluu-server/etc/hostname.original /opt/gluu-server/etc/hostname
  else
    if [ -n "$RUN_VERSION" ] && [ "$RUN_VERSION" != "$VERSION" ]; then
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'useradd ldap -d /home/ldap'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'useradd jetty -d /home/jetty'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'useradd node -d /home/node'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'useradd radius -d /opt/gluu/radius'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'groupadd gluu  '
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'gpasswd -a ldap gluu'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'gpasswd -a node gluu'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'gpasswd -a jetty gluu'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'gpasswd -a ldap adm'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'gpasswd -a radius gluu'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'gpasswd -a ldap adm'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /opt/jetty ] && chown -R jetty:jetty /opt/jetty*'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /opt/gluu/jetty ] && chown -R jetty:jetty /opt/gluu/jetty'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /opt/gluu/jetty ] && chmod -R 755 /opt/gluu/jetty'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /opt/shibboleth-idp ] && chown -R jetty:jetty /opt/shibboleth-idp'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs ] && chown -R root:gluu /etc/certs'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/oxauth-keys.jks ] && chown -R jetty:jetty /etc/certs/oxauth-keys.jks'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /opt/opendj ] && chown -R ldap:ldap /opt/opendj'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /opt/node ] && chown -R node:node /opt/node*'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /opt/gluu/node ] && chown -R node:node /opt/gluu/node'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /opt/gluu/node ] && chmod -R 755 /opt/gluu/node'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /opt/gluu/radius ] && chown -R radius:ldap /opt/gluu/radius'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /opt/gluu/radius ] && chmod -R a+rx /opt/gluu/radius'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /home/ldap ] && chown ldap:ldap /home/ldap'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /home/node ] && chown node:node /home/node'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /home/jetty ] && chown jetty:jetty /home/jetty'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/profile ] && chmod 644 /etc/profile'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /tmp ] && chmod ga+w /tmp'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/gluu/ ] && chown root:gluu /var/gluu/'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/gluu/ ] && chmod 755 /var/gluu/'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/gluu/photos ] && chown root:gluu /var/gluu/photos'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/gluu/photos ] && chmod 775 /var/gluu/photos'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/gluu/identity ] && chown -R root:gluu /var/gluu/identity'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/gluu/identity ] && chmod -R 775 /var/gluu/identity'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/run ] && chown root:root /var/run '
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/run/jetty ] && chown root:jetty /var/run/jetty'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/run/jetty ] && chown jetty:jetty /var/run/jetty/*'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/run/radius ] && chown root:root /var/run/radius'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/run/ ] && chmod 755 /var/run/'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/run/jetty ] && chmod 775 /var/run/jetty'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/run/jetty ] && chmod 644 /var/run/jetty/*'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /var/run/radius ] && chmod 775 /var/run/radius'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/httpd.key.orig ] && chown jetty:jetty /etc/certs/httpd.key.orig'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/httpd.key.orig ] && chmod 700 /etc/certs/httpd.key.orig'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/httpd.key ] && chown jetty:jetty /etc/certs/httpd.key'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/httpd.key ] && chmod 700 /etc/certs/httpd.key'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/shibIDP.key.orig ] && chown jetty:jetty /etc/certs/shibIDP.key.orig'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/shibIDP.key.orig ] && chmod 700 /etc/certs/shibIDP.key.orig'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/shibIDP.key ] && chown jetty:jetty /etc/certs/shibIDP.key'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/shibIDP.key ] && chmod 700 /etc/certs/shibIDP.key'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/idp-encryption.key.orig ] && chown jetty:jetty /etc/certs/idp-encryption.key.orig'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/idp-encryption.key.orig ] && chmod 700 /etc/certs/idp-encryption.key.orig'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/idp-encryption.key ] && chown jetty:jetty /etc/certs/idp-encryption.key'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/idp-encryption.key ] && chmod 700 /etc/certs/idp-encryption.key'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/idp-signing.key.orig ] && chown jetty:jetty /etc/certs/idp-signing.key.orig'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/idp-signing.key.orig ] && chmod 700 /etc/certs/idp-signing.key.orig'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/idp-signing.key ] && chown jetty:jetty /etc/certs/idp-signing.key'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/idp-signing.key ] && chmod 700 /etc/certs/idp-signing.key'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/passport-sp.key.orig ] && chown ldap:ldap /etc/certs/passport-sp.key.orig'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/passport-sp.key.orig ] && chmod 700 /etc/certs/passport-sp.key.orig'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/passport-sp.key ] && chown ldap:ldap /etc/certs/passport-sp.key'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/passport-sp.key ] && chmod 700 /etc/certs/passport-sp.key'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/shibIDP.pkcs12 ] && chown jetty:jetty /etc/certs/shibIDP.pkcs12'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/shibIDP.pkcs12 ] && chmod 700 /etc/certs/shibIDP.pkcs12'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/shibIDP.jks ] && chown jetty:jetty /etc/certs/shibIDP.jks'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/shibIDP.jks ] && chmod 700 /etc/certs/shibIDP.jks'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs ] && chown jetty:jetty /etc/certs'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /install/community-edition-setup/output/oxauth-keys.json ] && chown jetty:jetty /install/community-edition-setup/output/oxauth-keys.json'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /install/community-edition-setup/output/oxauth-keys.json ] && chmod 500 /install/community-edition-setup/output/oxauth-keys.json'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/hostname ] && chmod 644 /etc/hostname'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/hosts ] && chmod 644 /etc/hosts'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /home/ldap/.pw ] && chown ldap:ldap /home/ldap/.pw'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs ] && chown root:gluu /etc/certs'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/gluu/conf ] && chown root:gluu /etc/gluu/conf'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs ] && chmod 440 /etc/certs'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs ] && chmod a+x /etc/certs'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/gluu-radius.jks ] && chown radius:gluu /etc/certs/gluu-radius.jks'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/gluu-radius.private-key.pem ] && chown radius:gluu /etc/certs/gluu-radius.private-key.pem'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/oxauth-keys.jks ] && chown jetty:jetty /etc/certs/oxauth-keys.jks'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/oxauth-keys.jks ] && chmod 660 /etc/certs/oxauth-keys.jks'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/init.d/opendj ] && chmod +x /etc/init.d/opendj'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/default/oxauth ] && chown root:root /etc/default/oxauth'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/init.d/oxauth ] && chmod +x /etc/init.d/oxauth'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /usr/lib/tmpfiles.d/jetty.conf ] && chown root:root /usr/lib/tmpfiles.d/jetty.conf'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /usr/lib/tmpfiles.d/jetty.conf ] && chmod 644 /usr/lib/tmpfiles.d/jetty.conf'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/default/identity ] && chown root:root /etc/default/identity'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/init.d/identity ] && chmod +x /etc/init.d/identity'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /usr/lib/tmpfiles.d/jetty.conf ] && chown root:root /usr/lib/tmpfiles.d/jetty.conf'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /usr/lib/tmpfiles.d/jetty.conf ] && chmod 644 /usr/lib/tmpfiles.d/jetty.conf'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/default/idp ] && chown root:root /etc/default/idp'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/init.d/idp ] && chmod +x /etc/init.d/idp'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /usr/lib/tmpfiles.d/jetty.conf ] && chown root:root /usr/lib/tmpfiles.d/jetty.conf'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /usr/lib/tmpfiles.d/jetty.conf ] && chmod 644 /usr/lib/tmpfiles.d/jetty.conf'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/default/passport ] && chown root:root /etc/default/passport'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/init.d/passport ] && chmod +x /etc/init.d/passport'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/init.d/gluu-radius ] && chmod +x /etc/init.d/gluu-radius'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/gluu/conf/radius/ ] && chown root:gluu /etc/gluu/conf/radius/'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/gluu-radius.jks ] && chown radius:gluu /etc/certs/gluu-radius.jks'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/gluu-radius.private-key.pem ] && chown radius:gluu /etc/certs/gluu-radius.private-key.pem'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/oxauth-keys.jks ] && chown radius:gluu /etc/certs/oxauth-keys.jks'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/oxauth-keys.jks ] && chmod 660 /etc/certs/oxauth-keys.jks'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/gluu-radius.jks ] && chmod 660 /etc/certs/gluu-radius.jks'
      /usr/sbin/chroot /opt/gluu-server /bin/su - root -c '[ -e /etc/certs/gluu-radius.private-key.pem ] && chmod 660 /etc/certs/gluu-radius.private-key.pem'
      /etc/init.d/gluu-server stop
      /etc/init.d/gluu-server start 
    fi
  fi
fi

exit 0
