#!/bin/bash

set -e

echo "Checking to make sure Gluu Server is down..."

case $1 in
    remove)  
        if [ -f /sbin/gluu-serverd-4.0 ]; then
            /sbin/gluu-serverd-4.0 stop
        fi
        if [ -d /opt/gluu-server-4.0.save ] ; then
            rm -rf /opt/gluu-server-4.0.save
        fi
        if [ -d /opt/gluu-server-4.0 ] ; then
	    echo "Your changes will be saved into /opt/gluu-server-4.0.saved"
            mv /opt/gluu-server-4.0 /opt/gluu-server-4.0.save
        fi
        exit 0
        ;;
    deconfigure|upgrade)
        if [ -f /sbin/gluu-serverd-4.0 ]; then
		/sbin/gluu-serverd-4.0 stop
        fi
	exit 0
        ;;
    failed-upgrade)
        exit 2
        ;;
    *)
        echo "Prerm called with unknown argument '$1'" >&2
        exit 0
        ;;
esac
exit $?
