#!/bin/bash

if [ "$1" = "remove" ] ; then
    if [ -f /etc/init.d/gluu-server-4.0 ] ; then
        rm -rf /etc/init.d/gluu-server-4.0
    fi

    if [ -f /sbin/gluu-serverd-4.0 ] ; then
        rm -rf /sbin/gluu-serverd-4.0
    fi
fi
exit 0
