#!/bin/bash

if [ "$1" = "remove" ] ; then
    if [ -f /etc/init.d/gluu-server ] ; then
        update-rc.d gluu-server remove
        rm -rf /etc/init.d/gluu-server
    fi

    if [ -f /sbin/gluu-serverd ] ; then
        rm -rf /sbin/gluu-serverd
    fi
    
    if [ -f /lib/systemd/system/systemd-nspawn@gluu_server.service ]; then
        systemctl disable systemd-nspawn@gluu_server.service        
        rm -rf /lib/systemd/system/systemd-nspawn@gluu_server.service
        rm -rf /var/lib/container/gluu_server        
    fi
    
    rm -rf /var/lib/dpkg/info/gluu-server.*
fi
exit 0
