#!/bin/bash
set -e

# Setting package version
VERSION='%VERSION%'
RUN_VERSION=$2
ARG=$1

/usr/sbin/chroot /opt/gluu-server /bin/su - root -c '/tmp/system_user.list' > /dev/null 2>&1
/usr/sbin/chroot /opt/gluu-server /bin/su - root -c '/tmp/system_group.list' > /dev/null 2>&1
/usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'chmod 777 /tmp' > /dev/null 2>&1
/usr/sbin/chroot /opt/gluu-server /bin/su - root -c 'chown -R man /var/cache/man' > /dev/null 2>&1

# gluu-serverd
mkdir -p /sbin/
/bin/cp /opt/gluu-server/tmp/gluu-serverd /sbin/
rm -rf /opt/gluu-server/tmp/gluu-serverd

# systemd unit file
mkdir -p /lib/systemd/system/
/bin/cp /opt/gluu-server/tmp/systemd-unitfile /lib/systemd/system/systemd-nspawn@gluu_server.service
systemctl enable machines.target
systemctl enable systemd-nspawn@gluu_server.service
rm -rf /opt/gluu-server/tmp/systemd-unitfile

sed -i 's/.*Storage.*/Storage=persistent/g' /etc/systemd/journald.conf
systemctl restart systemd-journald
if [[ ! -d /var/lib/container ]]; then
  mkdir -p /var/lib/container
fi
ln -s /opt/gluu-server /var/lib/container/gluu_server

if [[ -d /etc/gluu/keys ]]; then
  rm -rf /etc/gluu/keys
  mkdir -p /etc/gluu/keys
else
  mkdir -p /etc/gluu/keys
fi
ssh-keygen -b 2048 -t rsa -f /etc/gluu/keys/gluu-console -q -N ""
if [[ ! -d /opt/gluu-server/root/.ssh ]]; then
  mkdir -p /opt/gluu-server/root/.ssh
  chmod 700 /opt/gluu-server/root/.ssh
fi
cat /etc/gluu/keys/gluu-console.pub > /opt/gluu-server/root/.ssh/authorized_keys
chmod 600 /opt/gluu-server/root/.ssh/authorized_keys
chmod 400 /opt/gluu-server/etc/ssh/ssh_host_rsa_key
chmod 400 /opt/gluu-server/etc/ssh/ssh_host_ecdsa_key
chmod 400 /opt/gluu-server/etc/ssh/ssh_host_ed25519_key

/bin/cp /etc/resolv.conf /opt/gluu-server/etc/ > /dev/null 2>&1

if [ "$1" = "configure" ]; then
  if [ -z "$RUN_VERSION" ] || [ "$RUN_VERSION" = "$VERSION" ]; then
    echo "Starting gluu-server ..."
    sleep 1
    gluu-serverd start
    sleep 4
    ssh -t -o IdentityFile=/etc/gluu/keys/gluu-console -o Port=60022 -o LogLevel=QUIET \
                -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
                -o PubkeyAuthentication=yes root@localhost '/opt/gluu/bin/install.py'  
  fi
fi

exit 0
