#!/bin/bash

if [ "$1" != "upgrade" ] ; then
    if [ "$1" = "purge" ] ; then
        if [ -d /opt/gluu-server-3.1.5.save ] ; then
            echo "Removing saved changes /opt/gluu-server-3.1.5.save"
            rm -rf /opt/gluu-server-3.1.5.save
        fi
    else 
        if [ -f /etc/init.d/gluu-server-3.1.5 ] ; then
            rm -rf /etc/init.d/gluu-server-3.1.5
        fi

        if [ -f /sbin/gluu-serverd-3.1.5 ] ; then
            rm -rf /sbin/gluu-serverd-3.1.5
        fi
    
        if [ -d /opt/gluu-server-3.1.5.save ] ; then
            rm -rf /opt/gluu-server-3.1.5.save
        fi

        if [ -d /opt/gluu-server-3.1.5 ] ; then
            mv /opt/gluu-server-3.1.5 /opt/gluu-server-3.1.5.save
            echo "Your changes will be saved into /opt/gluu-server-3.1.5.save"
        fi
    fi
fi
mkdir -p /opt
exit 0
