name: Publish packages

on:
  push:
    tags:
    - 'v**'

  workflow_dispatch:

jobs:
  publish_binary_packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [ubuntu20]

        include:
          - name: ubuntu20
            asset_suffix: _amd64.deb
            build_files: deb/focal
            asset_prefix: '_'
            asset_path: gluu-server-nochroot
            sign_cmd: dpkg-sig -s builder -k DE92BEF14A1A4E542F678B64DC3C790386C73900
            python_version: 3.8

    steps:
    - name: Getting build dependencies
      id: get_dependencies
      run: |      
         git clone -b gluu-server-nochroot https://github.com/GluuFederation/packaging
         mkdir -p gluu-server-nochroot/gluu-server-nochroot-src/opt/
         cp -rp packaging/${{ matrix.build_files }}/* gluu-server-nochroot/
         wget https://raw.githubusercontent.com/GluuFederation/community-edition-setup/version_4.4.0/gluu_install.py -O gluu-server-nochroot/install.py
         sudo add-apt-repository ppa:deadsnakes/ppa
         sudo apt-get update
         sudo apt-get install -y python${{ matrix.python_version }}
         sudo apt install -y build-essential devscripts debhelper rpm dpkg-sig python3-ldap3 python3-requests python3-ruamel.yaml python3-pymysql python3-crypto python3-distutils python3-prompt-toolkit
    - name: Get latest tag
      id: previoustag
      run: |
        echo "::set-output name=version::$(echo 4.4.0)"
    - name: Print Version
      run: |
        echo "${{ steps.previoustag.outputs.version }}"
    - name: Running install and build
      id: run_build
      run: |
         cd gluu-server-nochroot/
         sudo rm -rf /etc/systemd/system/*
         sudo python${{ matrix.python_version }} install.py --no-setup -a --jetty-version=10.0.9 
         mkdir -p gluu-server-nochroot-src/opt/ gluu-server-nochroot-src/etc/certs/ gluu-server-nochroot-src/etc/systemd/ gluu-server-nochroot-src/usr/bin/
         cp -r /opt/dist gluu-server-nochroot-src/opt/
         cp -r /opt/gluu gluu-server-nochroot-src/opt/
         cp -r /etc/certs/casa.pub gluu-server-nochroot-src/etc/certs/
         cp -r /etc/systemd/system/* gluu-server-nochroot-src/etc/systemd/
         ls gluu-server-nochroot-src/etc/systemd/system/
         cp -r /usr/bin/facter gluu-server-nochroot-src/usr/bin/
         rm -rf install.py
         sed -i "s/%VERSION%/${{ steps.previoustag.outputs.version }}/g" run-build.sh
         cat run-build.sh
         sudo ./run-build.sh
    - name: Create checksum
      id: create_checksum
      run: |
        cd gluu-server-nochroot/
        sed -i "s/%VERSION%/${{ steps.previoustag.outputs.version }}/g" checksum.sh
        sudo ./checksum.sh      
    - name: Upload binaries to release
      id: upload_binaries
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/${{ matrix.asset_path }}/gluu-server-nochroot${{ matrix.asset_prefix }}${{ steps.previoustag.outputs.version }}${{ matrix.asset_suffix }}
        asset_name: gluu-server-nochroot${{ matrix.asset_prefix }}${{ steps.previoustag.outputs.version }}${{ matrix.asset_suffix }}
        tag: ${{ steps.previoustag.outputs.tag }}
    - name: Upload checksum to release
      id: upload_shas
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/${{ matrix.asset_path }}/gluu-server-nochroot${{ matrix.asset_prefix }}${{ steps.previoustag.outputs.version }}${{ matrix.asset_suffix }}.sha256sum
        asset_name: gluu-server-nochroot${{ matrix.asset_prefix }}${{ steps.previoustag.outputs.version }}${{ matrix.asset_suffix }}.sha256sum
        tag: ${{ steps.previoustag.outputs.tag }}
